-- =========================================================
-- ESQUEMA DE BASE DE DATOS PARA SUPABASE
-- Mi Alcancía & Control de Gastos Mensuales
-- =========================================================

-- 1. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    activo INTEGER DEFAULT 1,
    rol TEXT DEFAULT 'usuario',
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabla de Configuración (sueldos, metas por usuario)
CREATE TABLE IF NOT EXISTS configuracion (
    clave TEXT PRIMARY KEY,
    valor TEXT NOT NULL
);

-- 3. Tabla de Gastos
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    descripcion TEXT NOT NULL,
    categoria TEXT NOT NULL,
    icono TEXT NOT NULL,
    monto NUMERIC NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Políticas de Acceso (Row Level Security)
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;

-- Políticas para permitir operaciones desde la aplicación cliente (API Anon / Service)
DROP POLICY IF EXISTS "Acceso total usuarios" ON usuarios;
CREATE POLICY "Acceso total usuarios" ON usuarios FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total configuracion" ON configuracion;
CREATE POLICY "Acceso total configuracion" ON configuracion FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total gastos" ON gastos;
CREATE POLICY "Acceso total gastos" ON gastos FOR ALL USING (true) WITH CHECK (true);
