-- =========================================================
-- ESQUEMA DE BASE DE DATOS PARA SUPABASE
-- Mi Alcancía & Control de Gastos Mensuales
-- =========================================================

-- 1. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    activo INTEGER DEFAULT 1,
    rol TEXT DEFAULT 'usuario',
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabla de Configuración (sueldos, metas por usuario)
CREATE TABLE IF NOT EXISTS configuracion (
    clave TEXT PRIMARY KEY,
    valor TEXT NOT NULL
);

-- 3. Tabla de Gastos
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    descripcion TEXT NOT NULL,
    categoria TEXT NOT NULL,
    icono TEXT NOT NULL,
    monto NUMERIC NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Tabla de Pagos Fijos Mensuales
CREATE TABLE IF NOT EXISTS pagos_fijos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE DEFAULT 1,
    nombre TEXT NOT NULL,
    monto NUMERIC NOT NULL,
    categoria TEXT NOT NULL,
    icono TEXT NOT NULL,
    dia_desde INTEGER NOT NULL DEFAULT 1,
    dia_hasta INTEGER NOT NULL DEFAULT 10,
    activo INTEGER DEFAULT 1,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Historial de Pagos Fijos Pagados
CREATE TABLE IF NOT EXISTS pagos_fijos_historial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_fijo_id BIGINT REFERENCES pagos_fijos(id) ON DELETE CASCADE,
    mes INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    fecha_pago DATE NOT NULL,
    monto NUMERIC NOT NULL,
    UNIQUE(pago_fijo_id, mes, anio)
);

-- 6. Políticas de Acceso (Row Level Security)
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagos_fijos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagos_fijos_historial ENABLE ROW LEVEL SECURITY;

-- Políticas para permitir operaciones desde la aplicación cliente (API Anon / Service)
DROP POLICY IF EXISTS "Acceso total usuarios" ON usuarios;
CREATE POLICY "Acceso total usuarios" ON usuarios FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total configuracion" ON configuracion;
CREATE POLICY "Acceso total configuracion" ON configuracion FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total gastos" ON gastos;
CREATE POLICY "Acceso total gastos" ON gastos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total pagos_fijos" ON pagos_fijos;
CREATE POLICY "Acceso total pagos_fijos" ON pagos_fijos FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Acceso total pagos_fijos_historial" ON pagos_fijos_historial;
CREATE POLICY "Acceso total pagos_fijos_historial" ON pagos_fijos_historial FOR ALL USING (true) WITH CHECK (true);
